kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: ita-taxonomy-browser
  namespace: mdsnamespace
spec:
  replicas: 1
  strategy:
    rollingUpdate: 
      maxSurge: 1 
      maxUnavailable: 1 
  minReadySeconds: 5  
  template:
    metadata:
      labels:
        app: ita-taxonomy-browser
    spec:
      containers:
      - name: ita-taxonomy-browser
        image: itadevacr.azurecr.io/ita-taxonomy-browser/web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      restartPolicy: Always
---

kind: Service
apiVersion: v1
metadata:
  name: ita-taxonomy-browser
  namespace: mdsnamespace
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
  selector:
    app: ita-taxonomy-browser
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ita-taxonomy-browser
  namespace: mdsnamespace
spec:
  rules:
    - host: taxonomy-browser-dev.trade.gov
      http:
        paths:
          - backend:
              serviceName: ita-taxonomy-browser
              servicePort: 80
            path: /
  tls:
      - secretName: trade-gov-tls-secret
